version: '2'
services:
  garagem:
    build: .
    image: bellacia
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code/
    links:
      - redis
      - postgres
    command: python3 manage.py runserver 0.0.0.0:8000
  redis:
    image: redis
  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bellacia
      - POSTGRES_PASSWORD=bellacia
      - POSTGRES_DB=bellacia
