# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 23:08
from __future__ import unicode_literals

import bellacia.hooker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email', 'E-mail'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=6)),
                ('contact', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hooker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to=bellacia.hooker.models.hooker_picture_directory)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hooker',
            name='services',
            field=models.ManyToManyField(to='hooker.Service'),
        ),
        migrations.AddField(
            model_name='contact',
            name='hooker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hooker.Hooker'),
        ),
    ]
