# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 16:32
from __future__ import unicode_literals

import bellacia.model.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'E-mail'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=6, verbose_name='Tipo de contato')),
                ('contact', models.CharField(max_length=254, verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('picture', models.ImageField(null=True, upload_to=bellacia.model.models.model_picture_directory, verbose_name='Foto')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('height', models.FloatField(verbose_name='Altura')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('character', models.ManyToManyField(to='model.Character')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Model'),
        ),
    ]
