# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hooker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='section-photos')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0.99, max_digits=5)),
                ('hooker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hooker.Hooker')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='section-videos')),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essay.Section')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essay.Section'),
        ),
    ]
